---
dev_addr: "127.0.0.1:8001"
site_name: "Aughrim Hall Residents Association - How-Tos"
site_description: "ZtpOps - Ztp Ops"
site_url: "https://aughrimhallra.github.io/"
repo_url: "https://github.com/aughrimhallra/aughrimhallra.github.io"
edit_uri: "blob/develop/docs/"
repo_name: "aughrimhallra/aughrimhallra.github.io"
# ==================================================================================================================================
#   Ignore and do not change anything above this line, these are the standard settings that should be in place for our documentation
# ==================================================================================================================================

# Create your menu items here.

nav:
  - Introduction: "index.md"
  - Email Settings:
    - Windows:
      - Outlook: "outlook-on-windows.md"
      - Windows Mail: "mail-on-windows.md"
    - macOS:
      - Outlook: "outlook-on-mac.md"
      - Mac Mail: "mail-on-mac.md"

# ==================================================================================================================================
#   Ignore and do not change anything below this line, these are the standard settings that should be in place for our documentation
# ==================================================================================================================================

# ==================================================================================================================================
# Setting up the basic NAT docs theme  <i class="fa-solid fa-house-chimney-user"></i>
theme:
  icon:
    logo: fontawesome/solid/house-chimney-user
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - navigation.tracking

# ==================================================================================================================================
# Setting up the basic plugins
plugins:
  - search
  - autorefs
  - mkdocstrings

extra:
  version:
    provider: mike


# ==================================================================================================================================
# Setting up the required markdown extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg